### ISSUE TITLE
Note geolocation not matching location

### ISSUE THREAD

**Issue by smhernandez** [scalableinternetservices/MapKeep#32]
As far as I can tell whenever I click on the Drop Note tab, it changes the drop location. Also the initial location was incorrect (could it be based on where the center of your map is on your browser?).

**Comment by DxTania** [comment]
What do you mean it changes the drop location? The button is supposed to drop it in the center of the map, and then you can move it around. The initial location is supposed to be either UCLA or the location of your first note (for now, but i'll change it to current location). Did I misunderstand your question?

**Comment by smhernandez** [comment]
Ahh, no, I think the functionality is sufficient then. My first note was at 0,0, so it dropped the new note there.. and then I didn't realize that I was supposed to manually move the marker. Meanwhile, if I clicked "drop note" over and over again, it would slightly move the map and continually drop the marker in the center (which was different each time).

How about we adjust this issue to "Marker does not drop at current location." OR perhaps we drop it to the center of the map & have an option "Move marker to current location" so that the user doesn't have to figure out where they are (especially if the map is currently in Fiji or something).

**Comment by DxTania** [comment]
This is what I originally intended, just hadn't done it yet. Does it make sense?

The map loads at current location by default (centered around current location). As you move the map around clicking 'Drop Pin' drops it in the center of the map. Maybe I can add something to make it more obvious that you can move it (ideas?). And then a button on the map or sidebar that returns the map to the user's current location.

**Comment by acmiyaguchi** [comment]
What about a double click to drop it at a specific location on the map, and a 'Drop Pin' button that sets it to the current location. If you were to do this from a mobile application perspective, a user would ideally just make a note that drops it in their current location. 

Also, possibly have an optional overlay ui like this site: http://www.runningmap.com/beta/

**Comment by DxTania** [comment]
And what happens when you move the map and click 'Drop Pin'? I think we should at least come up with something to make these things obvious to anyone using the app. But yeah a double click or maybe right click would work for dropping at a specific location.

About the overlays, I think we should stay away from that for now. Maybe a few things can fit there (like a search functionality maybe).

About centering on the user's location:
- navigator.geolocation is slow, and doesn't work until user visits webpage, so can't use that
- need a way (maybe by ip) for rails to know location before serving up notes

**Comment by DxTania** [comment]
Ok so pull request #33 uses ip location and fixes a couple things. @smhernandez can you take a look? The only problem with this is when you visit the site from the development machine the ip is always 127.0.0.1, so in order to mimic what it will do just put your ip on line 7 of the IndexController and we can remove this code later or figure out a way to get a non-localhost ip address. Haven't modified any buttons or drop location yet.

**Comment by DxTania** [comment]
geolocation implemented in pull request #33 
For issues regarding functionality of the map, please open a more specific issue so we can actually finalize how it should work
